# Generated by Django 2.1 on 2021-01-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201225_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('second', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
            ],
        ),
    ]
