# Generated by Django 2.1 on 2021-01-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='first',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='second',
        ),
        migrations.AlterField(
            model_name='sum',
            name='first',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='sum',
            name='second',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
