# Generated by Django 2.1 on 2021-01-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210102_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sum',
            name='first',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
