# Generated by Django 2.1 on 2021-01-04 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210102_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cargo',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
